### ISSUE TITLE
WeBWorK 3 backend to-do list

### ISSUE THREAD

**Issue by drdrew42** [openwebwork/webwork3#110]
- [ ] refactor relationships for plural/singular relation names
- [ ] update all instances of validation to use new `Validation.pm`
- [ ] use `->insert` wherever `->new(...)` is used
- [ ] add `fetch_with_defaults` as an alias for `discard_changes` and employ everywhere `add_to_$rel` is used
- [ ] eliminate dependency on `List::MoreUtils` (~~firstval~~)
- [ ] update all `$self` to use more appropriate naming convention

**Comment by drdrew42** [comment]
@pstaabp @drgrice1 feel free to add to this checklist 🙏

**Comment by pstaabp** [comment]
I just edited the list above.

**Comment by drdrew42** [comment]
`discard_changes` is no longer needed, now that we've added `retrieve_on_insert => 1` to all columns with default values. Please keep this in mind for any future DB changes that involve default values.
